/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './components/**/*.{js,vue}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#603100',
        'inverse-primary': '#a6c8ff',
        'surface-container-low': '#eff4ff',
        'on-primary': '#ffffff',
        secondary: '#904d00',
        'on-background': '#0b1c30',
        background: '#f8f9ff',
        'tertiary-fixed-dim': '#81cfff',
        'on-primary-container': '#7ea5e2',
        'inverse-surface': '#213145',
        'on-primary-fixed': '#001c3b',
        'primary-fixed-dim': '#a6c8ff',
        'primary-fixed': '#d5e3ff',
        'on-tertiary-fixed': '#001e2d',
        'surface-tint': '#355f97',
        error: '#ba1a1a',
        'tertiary-container': '#003e58',
        'secondary-container': '#fd8b00',
        'surface-bright': '#f8f9ff',
        tertiary: '#002739',
        'on-secondary-fixed': '#2f1500',
        'on-tertiary-container': '#26aeec',
        surface: '#f8f9ff',
        'secondary-fixed-dim': '#ffb77d',
        'on-tertiary-fixed-variant': '#004c6b',
        'outline-variant': '#c3c6d1',
        'surface-variant': '#d3e4fe',
        'surface-container': '#e5eeff',
        'inverse-on-surface': '#eaf1ff',
        'surface-dim': '#cbdbf5',
        'tertiary-fixed': '#c6e7ff',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        outline: '#737781',
        'on-primary-fixed-variant': '#18477e',
        'surface-container-highest': '#d3e4fe',
        'on-secondary-fixed-variant': '#6e3900',
        'on-error-container': '#93000a',
        'secondary-fixed': '#ffdcc3',
        'surface-container-high': '#dce9ff',
        primary: '#00244a',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#434750',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'primary-container': '#003a70',
        'on-surface': '#0b1c30',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'margin-desktop': '40px',
        gutter: '24px',
        base: '8px',
        'container-max': '1280px',
      },
      fontFamily: {
        'public-sans': ['Public Sans', 'sans-serif'],
        'title-lg': ['Public Sans'],
        'label-md': ['Public Sans'],
        'body-lg': ['Public Sans'],
        'headline-md': ['Public Sans'],
        'headline-lg': ['Public Sans'],
        'body-md': ['Public Sans'],
        'display-md': ['Public Sans'],
        'label-sm': ['Public Sans'],
        'display-lg': ['Public Sans'],
      },
      fontSize: {
        'title-lg': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-md': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.04em', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
